### ISSUE TITLE
Decomposition for 捗

### ISSUE THREAD

**Issue by glandium** [cjkvi/cjkvi-ids#21]
It currently is
```
⿰扌步[GTK]	⿰扌歩[J]
```

But the 常用漢字表 explicitly says the form for that character doesn't match that of 歩, so it seems it should simply be
```
⿰扌步
```
(Although my electronic version of the 漢字源 dictionary, which is older than 2010, does show the extra stroke)

**Comment by hfhchan** [comment]
I can confirm the extra dot is not on the newest Code Charts.  The glyph must have been updated in the newest revision.

**Comment by kawabata** [comment]
The right side of "捗" component has been "歩" for more than 20 years in the UCS, and still a majority
of fonts published since then follows this.  To preserve history and diversity, I will preserve this entry
(no problem for searching, in anyway.)
I admit that [J] tag might be inappropriate, and will consider something like [O] (obosolete) or something.

**Comment by kawabata** [comment]
I introduced [O] tag for this.
